# Generated by Django 4.0.2 on 2022-04-16 23:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('user_type', models.CharField(choices=[('P', 'Patient'), ('D', 'Doctor'), ('R', 'Receptionist')], max_length=1)),
                ('birthday', models.DateField()),
                ('phone_num', models.CharField(max_length=14)),
                ('address', models.CharField(max_length=100)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='VaccinationAppointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appointment_date', models.DateTimeField(verbose_name='Appointment Date')),
                ('num_dose', models.IntegerField()),
                ('arm', models.CharField(blank=True, choices=[('R', 'Right'), ('L', 'Left')], max_length=1, null=True)),
                ('status', models.CharField(choices=[('PE', 'Pending'), ('CO', 'Confirmed'), ('CA', 'Canceled'), ('DO', 'Done')], default='PE', max_length=2)),
            ],
        ),
    ]
