# Generated by Django 4.0.2 on 2022-04-17 00:38

from django.db import migrations, models
import django.db.models.deletion
import patientapp.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('centreapp', '0002_initial'),
        ('patientapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vaccinationappointment',
            name='centre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='centreapp.vaccinecentre'),
        ),
        migrations.AddField(
            model_name='vaccinationappointment',
            name='doctor',
            field=models.ForeignKey(blank=True, limit_choices_to={'id__in': patientapp.models.Account.get_doctors_ids}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='d_appointments', to='patientapp.account'),
        ),
        migrations.AddField(
            model_name='vaccinationappointment',
            name='patient',
            field=models.ForeignKey(limit_choices_to={'id__in': patientapp.models.Account.get_patients_ids}, on_delete=django.db.models.deletion.CASCADE, related_name='p_appointments', to='patientapp.account'),
        ),
        migrations.AddField(
            model_name='vaccinationappointment',
            name='receptionist',
            field=models.ForeignKey(blank=True, limit_choices_to={'id__in': patientapp.models.Account.get_receptionists_ids}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='confirmed_app', to='patientapp.account'),
        ),
        migrations.AddField(
            model_name='vaccinationappointment',
            name='vaccine',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='centreapp.vaccine'),
        ),
        migrations.AddField(
            model_name='account',
            name='vaccine_centre',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='centreapp.vaccinecentre'),
        ),
    ]
