# Generated by Django 4.0.2 on 2022-04-07 23:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('centreapp', '0001_initial'),
        ('patientapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vaccinationappointment',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='centreapp.doctor'),
        ),
        migrations.AddField(
            model_name='vaccinationappointment',
            name='receptionist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='centreapp.receptionist'),
        ),
        migrations.AddField(
            model_name='vaccinationappointment',
            name='vaccine',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='centreapp.vaccine'),
        ),
        migrations.AddField(
            model_name='vaccinationappointment',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='patientapp.patient'),
        ),
    ]
