# Generated by Django 4.0.2 on 2022-06-18 12:00

from django.db import migrations, models
import django.db.models.deletion
import patientapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('patientapp', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vaccinationappointment',
            name='doctor',
            field=models.ForeignKey(blank=True, limit_choices_to=patientapp.models.limit_doctor_choices, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='d_appointments', to='patientapp.account'),
        ),
        migrations.AlterField(
            model_name='vaccinationappointment',
            name='patient',
            field=models.ForeignKey(limit_choices_to=patientapp.models.limit_patient_choices, on_delete=django.db.models.deletion.CASCADE, related_name='p_appointments', to='patientapp.account'),
        ),
        migrations.AlterField(
            model_name='vaccinationappointment',
            name='receptionist',
            field=models.ForeignKey(blank=True, limit_choices_to=patientapp.models.limit_receptionist_choices, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='confirmed_app', to='patientapp.account'),
        ),
    ]
