# Generated by Django 4.0.2 on 2022-07-03 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patientapp', '0003_alter_vaccinationappointment_doctor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='carte_nationale',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='account',
            name='passport',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
