# Generated by Django 4.0.2 on 2022-04-09 22:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patientapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('account', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='patientapp.account')),
            ],
        ),
        migrations.CreateModel(
            name='Survey',
            fields=[
                ('vaccination_appointment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='patientapp.vaccinationappointment')),
            ],
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('staff_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='centreapp.staff')),
            ],
            bases=('centreapp.staff',),
        ),
        migrations.CreateModel(
            name='Receptionist',
            fields=[
                ('staff_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='centreapp.staff')),
            ],
            bases=('centreapp.staff',),
        ),
        migrations.CreateModel(
            name='VaccineCentre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=100)),
                ('num_phone', models.CharField(max_length=500)),
                ('vaccination_appointment', models.ManyToManyField(to='patientapp.VaccinationAppointment')),
            ],
        ),
        migrations.CreateModel(
            name='Vaccine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('time_between_dose', models.IntegerField()),
                ('vaccine_centre', models.ManyToManyField(to='centreapp.VaccineCentre')),
            ],
        ),
        migrations.AddField(
            model_name='staff',
            name='vaccine_centre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='centreapp.vaccinecentre'),
        ),
    ]
