# Generated by Django 4.0.2 on 2022-04-26 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('centreapp', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workinghours',
            name='day_of_week',
            field=models.PositiveIntegerField(choices=[(5, 'Saturday'), (6, 'Sunday'), (0, 'Monday'), (1, 'Thursday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday')], verbose_name='day of week'),
        ),
    ]
