# Generated by Django 4.0.2 on 2022-06-18 12:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('centreapp', '0003_alter_workinghours_day_of_week'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workinghours',
            name='centre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='working_hours', to='centreapp.vaccinecentre'),
        ),
    ]
