# Generated by Django 4.0.2 on 2022-06-20 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('centreapp', '0004_alter_workinghours_centre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='survey',
            name='blood_pressure',
            field=models.CharField(blank=True, choices=[('H', 'Hypertension'), ('N', 'Normal'), ('H', 'Hypotension')], max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='survey',
            name='heart_rate',
            field=models.CharField(blank=True, choices=[('T', 'Tachycardie'), ('N', 'Normal'), ('B', 'Bradycardie')], max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='survey',
            name='oximetry',
            field=models.CharField(blank=True, choices=[('G', 'Bonne saturation'), ('B', 'Désaturation')], max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='survey',
            name='respiratory_rate',
            field=models.CharField(blank=True, choices=[('E', 'Eupneique'), ('D', 'Dyspnée'), ('B', 'Bradypnée')], max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='survey',
            name='temperature',
            field=models.CharField(blank=True, choices=[('F', 'Fébrile'), ('A', 'Apyrétique')], max_length=2, null=True),
        ),
    ]
